
build:
  version: "1.0"

app:
  mode: "dev"
  message: "Welcome to curemap accounts DEV env APIs"
  contactDetails:
    name: "{cipher}7ecc103dcf686154c17ea1710c14e64d9462b6bb44a727ad472ab52ab5a93ba511dd890a1cbb93808e180cb647511fce"